use rust_decimal::Decimal;
use crate::market_data::event::PriceEvent;
use crate::error::Result;

/// Signal generated by a strategy
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Signal {
    Buy,
    Sell,
    Hold,
}

/// Strategy trait that all trading strategies must implement
pub trait Strategy: Send + Sync {
    /// Generate trading signal based on price event
    fn signal(&self, event: &PriceEvent) -> Result<Signal>;

    /// Get strategy name
    fn name(&self) -> &str;

    /// Get risk parameters (entry price, stop loss distance, position size)
    fn get_risk_params(&self, current_price: Decimal) -> Result<(Decimal, Decimal, Decimal)>;
}
